gcc 4.4 complains about return value of index()
error: invalid conversion from 'const char*' to 'char*'

While index() and rindex() are specified as having a return
type of 'char*' gcc 4.4 complains when a 'const char*' is
used.  This makes sense because the return is a pointer
to the 'const char*' given as the first argument.

The code in question knows it is operating on a non-const
string so this will not a real problem as long as this
is true.

../remFileOpen.cc: In function 'int fileClose(FILE*)':
../remFileOpen.cc:358: warning: deprecated conversion from string constant to 'char*'
../remFileOpen.cc: In function 'int fileReadable(char*)':
../remFileOpen.cc:427: error: invalid conversion from 'const char*' to 'char*'
../remFileOpen.cc:429: error: invalid conversion from 'const char*' to 'char*'
../remFileOpen.cc:449: error: invalid conversion from 'const char*' to 'char*'
../remFileOpen.cc: In function 'void discardParams(char*, int)':
../remFileOpen.cc:482: error: invalid conversion from 'const char*' to 'char*'
../remFileOpen.cc:484: error: invalid conversion from 'const char*' to 'char*'
../remFileOpen.cc:506: error: invalid conversion from 'const char*' to 'char*'
../remFileOpen.cc: In function 'void getParams(char*, char*, int)':
../remFileOpen.cc:528: error: invalid conversion from 'const char*' to 'char*'
../remFileOpen.cc:530: error: invalid conversion from 'const char*' to 'char*'
../remFileOpen.cc:548: error: invalid conversion from 'const char*' to 'char*'
../remFileOpen.cc: In function 'void reassemble(char*, char*, char*, int)':
../remFileOpen.cc:570: error: invalid conversion from 'const char*' to 'char*'
../remFileOpen.cc: At global scope:
../remFileOpen.cc:365: warning: 'int checkForHttp(char*, char*)' defined but not used